import React from "react";

const ImportExcel = () => {
  return (
    <div
      id="data-excel"
      className="container tab-pane active d-flex justify-content-center text-center"
    >
      <div className="col-md-8 pb-4">
        <h1 className="pt-3 h2">Upload Excel File</h1>
        <p className="text-secondary">
          Before you upload your Excel document, make sure you have used the
          template produced/generated by the system; otherwise the system will
          not accept it. you will have to insert data manually.
        </p>
        <form>
          <div className="input-group mb-3">
            <div className="custom-file">
              <input
                type="file"
                className="custom-file-input"
                id="inputGroupFile01"
                aria-describedby="inputGroupFileAddon01"
              />
              <label className="custom-file-label" htmlFor="inputGroupFile01">
                Choose file
              </label>
            </div>
          </div>
          <button type="submit" className="btn btn-primary">
            Submit document
          </button>
        </form>
      </div>
    </div>
  );
};

export default ImportExcel;
